### ISSUE TITLE
Unable to load library 'hackrf-sweep': Native library (darwin/libhackrf-sweep.dylib) not found in resource path

### ISSUE THREAD

**Issue by All3xJ** [mossmann/hackrf#761]
### Steps to reproduce
1.Start hackrf-spectrum-analyzer sh file

### Expected behaviour
hackrf-spectrum-analyzer should recognize the HackRF.

### Actual behaviour
hackrf-spectrum-analyzer opens but it doesn't recognize it, and it raises a Java exception.

### Version information
**Operating system**:
MacOS Mojave

**hackrf_info output:**
```
$ hackrf_info 
hackrf_info version: unknown
libhackrf version: unknown (0.5)
Found HackRF
Index: 0
Serial number: 0000000000000000223c69dc2251094f
Board ID Number: 2 (HackRF One)
Firmware Version: 2018.01.1 (API:1.02)
Part ID Number: 0xa000cb3c 0x007c4f56
```

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.

hackrf-spectrum-analyzer version 1.5 (the latest)
https://github.com/pavsa/hackrf-spectrum-analyzer/

### Output
```
$ ./hackrf_sweep_spectrum_analyzer_linux.sh 
Persistent image set to 320x240
HackRFSweep thread stopped.
Starting hackrf_sweep... 2400-2500MHz 
hackrf_sweep params:  freq 2400-2500MHz  FFTBin 100000Hz  samples 8192  lna: 40 vga: 0 antenna_lna: false
Exception in thread "hackrf_sweep" java.lang.UnsatisfiedLinkError: Unable to load library 'hackrf-sweep': Native library (darwin/libhackrf-sweep.dylib) not found in resource path ([rsrc:./, jar:rsrc:miglayout15-swing.jar!/, jar:rsrc:jcommon-1.0.17.jar!/, jar:rsrc:jfreechart-1.0.14.jar!/, jar:rsrc:jna-4.5.1.jar!/])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:303)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:369)
	at jspectrumanalyzer.nativebridge.HackRFSweepNativeBridge.<clinit>(Unknown Source)
	at jspectrumanalyzer.HackRFSweepSpectrumAnalyzer.sweep(Unknown Source)
	at jspectrumanalyzer.HackRFSweepSpectrumAnalyzer.lambda$restartHackrfSweepExecute$6(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:832)
Persistent image set to 256x256
HackRFSweep thread stopped.
Processing thread stopped.

```
The program opens but HackRF appears "disconnected".

**Comment by miek** [comment]
This is out of scope for here (we don't have a libhackrf-sweep library). I see you've opened an issue on the hackrf-spectrum-analyzer repo, so hopefully they can help you there.
